### ISSUE TITLE
Microsoft Defender is blocking Arelle Installer on Windows 11

### ISSUE THREAD

**Issue by janparttimaa** [Arelle/Arelle#1374] opened 2024-10-10 05:26 UTC
### What happened?

When trying to install Arelle 2.31.6, Microsoft Defender is blocking the installer.
![Screenshot 2024-10-10 at 8 24 35](https://github.com/user-attachments/assets/81ef8659-48b2-45d0-9126-1b3b879479d6)

### Interface

GUI (arelleGUI)

### Version

2.31.6

### Download

GitHub release (bundled Python)

### Operating System

Windows

**Comment by janparttimaa** [comment] 2024-10-10 05:31
Screenshots from Microsoft Defender-console.
![Screenshot 2024-10-10 at 8 24 35](https://github.com/user-attachments/assets/ec2f1acb-fb84-445c-8a9c-020c6b532112)
![Screenshot 2024-10-10 at 8 28 09](https://github.com/user-attachments/assets/dbf7ae2d-ad36-4122-b949-03d7956f5046)
![Screenshot 2024-10-10 at 8 28 57](https://github.com/user-attachments/assets/2f07bee6-8504-46ba-9d25-11fcf5ca438d)
![Screenshot 2024-10-10 at 8 29 20](https://github.com/user-attachments/assets/578faf73-5768-453a-acac-bcb0ee956238)
![Screenshot 2024-10-10 at 8 29 40](https://github.com/user-attachments/assets/411d5f6a-9f6f-4731-84f2-1ca73a362a40)
![Screenshot 2024-10-10 at 8 30 07](https://github.com/user-attachments/assets/dffeb21a-06d3-4d68-b788-65cdbe64dd2c)
![Screenshot 2024-10-10 at 8 30 38](https://github.com/user-attachments/assets/3626c508-3bd9-41cc-992d-c7e5c35359a8)

Looks like signing certificate is missing from the installer. Would it possible to add that?

**Comment by janparttimaa** [comment] 2024-10-10 06:04
@austinmatherne-wk: Hello, I noticed that this issue is related to issue #1081 . Just out of curiosity, what is the current situation of signing the installer and is there any ETA when this will be resolved?

**Comment by austinmatherne-wk** [comment] 2024-10-10 13:05
Hi @janparttimaa,

Thank you for the reminder. We were waiting for the Azure signing service to be released. Right now, we're concentrating on a few projects with year-end deadlines, so it's unlikely we'll address this before then. However, I'll ensure it's a priority once those initiatives are complete.

**Comment by austinmatherne-wk** [comment] 2024-10-10 13:09
I'm going to close this as development will be handled by #1081. If you have additional questions please ask them there. Thanks!

Duplicate of #1081

**Closed by austinmatherne-wk** 2024-10-10 13:09 UTC
Labels: bug
