### ISSUE TITLE
Taxonomy package accepted by XMLSpy and Fujitsu is rejected by Arelle 

### ISSUE THREAD

**Issue by napalase** [Arelle/Arelle#848] opened 2023-08-28 15:09 UTC
### What happened?

I've tried to add a taxonomy package using the Taxonomy Packages Manager
An error is reported that the package is not itself a taxonomy package.

![image](https://github.com/Arelle/Arelle/assets/37013669/7959224f-6efc-4f95-b2ea-ada6b55d7114)

Other tools, like XMLSpy and Fujitsu, do accept this file as a valid taxonomy package.

System used is a virtual machine running Windows Server 2019 Standard.

### Documents

[DNB Custom Functions 1.0.0 (2020-04-15).zip](https://github.com/Arelle/Arelle/files/12455724/DNB.Custom.Functions.1.0.0.2020-04-15.zip)

### Interface

GUI (arelleGUI)

### Version

2.13.5 (64bit AMD64)

### Download

arelle.org (bundled Python)

### Operating System

Other (please specify)

**Comment by austinmatherne-wk** [comment] 2023-08-28 17:48
Hi,

I'm able to open the attached taxonomy package in Arelle (2.13.5) in a Windows VM. I noticed between the error message and the GitHub download link that GitHub appears to have normalized the filename, which might be responsible for the inconstancy between our results. Can you verify if you have the same issue if you download the package from GitHub?

<img width="865" alt="Screenshot 2023-08-28 at 1 42 39 PM" src="https://github.com/Arelle/Arelle/assets/46454775/2044be4f-4c55-495e-bd05-c9669f63e8ed">

**Comment by napalase** [comment] 2023-08-29 06:31
Hello Austin,

unfortunately not.

![image](https://github.com/Arelle/Arelle/assets/37013669/64f424da-23fe-4ed8-81fa-3c8fcd085acd)

Is access to internet required?
The only thing that I can think off that might be different is that this VM has no access to internet.

**Comment by napalase** [comment] 2023-08-29 06:33
Just noticed this error in the messages section.

![image](https://github.com/Arelle/Arelle/assets/37013669/635116dc-9c49-4d39-aab3-f97b4d1f9d83)

apparently access to internet is needed.
Is there a workaround for it?

**Comment by napalase** [comment] 2023-08-29 07:00
Moving the xsd into the arelle cache resolves the problem.

![image](https://github.com/Arelle/Arelle/assets/37013669/7ab3592e-5a3f-42cc-8bef-fee806a2bcb6)

**Comment by austinmatherne-wk** [comment] 2023-08-29 13:11
Ah, yes this is caused by #684. This should be resolved in the near future. I'm going to close this as a duplicate.

Thanks for reporting!

**Closed by austinmatherne-wk** 2023-08-29 13:11 UTC
Labels: bug
