### ISSUE TITLE
ESEF plugin should not apply the ESEF validation rules to facts with "target" attribute

### ISSUE THREAD

**Issue by IulianBogdan** [Arelle/Arelle#1041] opened 2024-01-16 13:05 UTC
### What happened?

When validating a report based on ESEF and DK GAAP I get the following error message:
`[ESEF.2.4.1.transformableElementIncludedInHiddenSection] The ix:hidden section of Inline XBRL document MUST not include elements eligible for transformation. 33 fact(s) were eligible for transformation: arr:SignatureOfAuditorsDate, arr:SignatureOfAuditorsPlace, arr:TypeOfBasisForModifiedOpinionOnAuditedFinancialStatements, arr:TypeOfModifiedOpinionOnAuditedFinancialStatements, cmn:DescriptionOfAuditor, cmn:IdentificationNumberCvrOfAuditFirm, cmn:IdentificationNumberOfAuditor, cmn:NameAndSurnameOfAuditor, cmn:NameOfAuditFirm, cmn:TypeOfAuditorAssistance, gsd:AddressOfReportingEntityDistrictName, gsd:AddressOfReportingEntityPostCodeIdentifier, gsd:AddressOfReportingEntityStreetBuildingIdentifier, gsd:AddressOfReportingEntityStreetName, gsd:AddressOfSubmittingEnterprisePostcodeAndTown, gsd:AddressOfSubmittingEnterpriseStreetAndNumber, gsd:DateOfGeneralMeeting, gsd:IdentificationNumberCvrOfReportingEntity, gsd:IdentificationNumberCvrOfSubmittingEnterprise, gsd:NameOfReportingEntity, gsd:NameOfSubmittingEnterprise, gsd:PrecedingReportingPeriodStartDate, gsd:PredingReportingPeriodEndDate, gsd:ReportingPeriodEndDate, gsd:ReportingPeriodStartDate, gsd:ToolForPreparingTheXBRLInstanceDocument, sob:DateOfApprovalOfAnnualReport, sob:PlaceOfSignatureOfStatement`

The error references to this section of the report:
`<ix:hidden>
					<ix:nonNumeric name="gsd:InformationOnTypeOfSubmittedReport" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Annual report</ix:nonNumeric>
					<ix:nonNumeric name="cmn:TypeOfAuditorAssistance" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Auditor&apos;s report on audited financial statements</ix:nonNumeric>
					<ix:nonNumeric name="gsd:ToolForPreparingTheXBRLInstanceDocument" target="DKGAAP" contextRef="ctx-1" xml:lang="en">ParsePort XBRL Converter</ix:nonNumeric>
					<ix:nonNumeric name="gsd:ReportingPeriodStartDate" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2022-04-01</ix:nonNumeric>
					<ix:nonNumeric name="gsd:ReportingPeriodEndDate" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2023-03-31</ix:nonNumeric>
					<ix:nonNumeric name="gsd:PrecedingReportingPeriodStartDate" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2021-04-01</ix:nonNumeric>
					<ix:nonNumeric name="gsd:PredingReportingPeriodEndDate" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2022-03-31</ix:nonNumeric>
					<ix:nonNumeric name="gsd:DateOfGeneralMeeting" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2023-09-29</ix:nonNumeric>
					<ix:nonNumeric name="gsd:NameOfReportingEntity" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Veloxis Pharmaceuticals A/S</ix:nonNumeric>
					<ix:nonNumeric name="fsa:ClassOfReportingEntity" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Reporting class B</ix:nonNumeric>
					<ix:nonNumeric name="gsd:IdentificationNumberCvrOfReportingEntity" target="DKGAAP" contextRef="ctx-1" xml:lang="en">26527767</ix:nonNumeric>
					<ix:nonNumeric name="gsd:AddressOfReportingEntityStreetName" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Langelinie Allé</ix:nonNumeric>
					<ix:nonNumeric name="gsd:AddressOfReportingEntityStreetBuildingIdentifier" target="DKGAAP" contextRef="ctx-1" xml:lang="en">35</ix:nonNumeric>
					<ix:nonNumeric name="gsd:AddressOfReportingEntityPostCodeIdentifier" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2100</ix:nonNumeric>
					<ix:nonNumeric name="gsd:AddressOfReportingEntityDistrictName" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Copenhagen</ix:nonNumeric>
					<ix:nonNumeric name="sob:PlaceOfSignatureOfStatement" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Copenhagen</ix:nonNumeric>
					<ix:nonNumeric name="sob:DateOfApprovalOfAnnualReport" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2023-09-29</ix:nonNumeric>
					<ix:nonNumeric name="gsd:IdentificationNumberCvrOfSubmittingEnterprise" target="DKGAAP" contextRef="ctx-1" xml:lang="en">33771231</ix:nonNumeric>
					<ix:nonNumeric name="gsd:NameOfSubmittingEnterprise" target="DKGAAP" contextRef="ctx-1" xml:lang="en">PricewaterhouseCoopers Statsautoriseret Revisionspartnerselskab</ix:nonNumeric>
					<ix:nonNumeric name="gsd:AddressOfSubmittingEnterpriseStreetAndNumber" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Strandvejen 44</ix:nonNumeric>
					<ix:nonNumeric name="gsd:AddressOfSubmittingEnterprisePostcodeAndTown" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2900 Hellerup</ix:nonNumeric>
					<ix:nonNumeric name="arr:TypeOfModifiedOpinionOnAuditedFinancialStatements" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Opinion</ix:nonNumeric>
					<ix:nonNumeric name="arr:TypeOfBasisForModifiedOpinionOnAuditedFinancialStatements" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Basis for Opinion</ix:nonNumeric>
					<ix:nonNumeric name="arr:SignatureOfAuditorsPlace" target="DKGAAP" contextRef="ctx-1" xml:lang="en">Copenhagen</ix:nonNumeric>
					<ix:nonNumeric name="arr:SignatureOfAuditorsDate" target="DKGAAP" contextRef="ctx-1" xml:lang="en">2023-09-29</ix:nonNumeric>
					<ix:nonNumeric name="cmn:NameAndSurnameOfAuditor" target="DKGAAP" contextRef="ctx-2" xml:lang="en">Søren Ørjan Jensen</ix:nonNumeric>
					<ix:nonNumeric name="cmn:DescriptionOfAuditor" target="DKGAAP" contextRef="ctx-2" xml:lang="en">State Authorised Public Accountant</ix:nonNumeric>
					<ix:nonNumeric name="cmn:IdentificationNumberOfAuditor" target="DKGAAP" contextRef="ctx-2" xml:lang="en">mne33226</ix:nonNumeric>
					<ix:nonNumeric name="cmn:IdentificationNumberCvrOfAuditFirm" target="DKGAAP" contextRef="ctx-2" xml:lang="en">33771231</ix:nonNumeric>
					<ix:nonNumeric name="cmn:NameOfAuditFirm" target="DKGAAP" contextRef="ctx-2" xml:lang="en">PricewaterhouseCoopers Statsautoriseret Revisionspartnerselskab</ix:nonNumeric>
					<ix:nonNumeric name="cmn:NameAndSurnameOfAuditor" target="DKGAAP" contextRef="ctx-3" xml:lang="en">Henrik Ødegaard</ix:nonNumeric>
					<ix:nonNumeric name="cmn:DescriptionOfAuditor" target="DKGAAP" contextRef="ctx-3" xml:lang="en">State Authorised Public Accountant</ix:nonNumeric>
					<ix:nonNumeric name="cmn:IdentificationNumberOfAuditor" target="DKGAAP" contextRef="ctx-3" xml:lang="en">mne31489</ix:nonNumeric>
					<ix:nonNumeric name="cmn:IdentificationNumberCvrOfAuditFirm" target="DKGAAP" contextRef="ctx-3" xml:lang="en">33771231</ix:nonNumeric>
					<ix:nonNumeric name="cmn:NameOfAuditFirm" target="DKGAAP" contextRef="ctx-3" xml:lang="en">PricewaterhouseCoopers Statsautoriseret Revisionspartnerselskab</ix:nonNumeric>
				</ix:hidden>`

This is expected behavior for ESEF, however, DK GAAP allows it. This should not be an error for the DBA authority.
Since ESEF facts don't have the "target" attribute, I believe a possible fix would be to not apply ESEF validation rules to targeted facts, instead relying on authority specific rules. This might be a general fix that I believe would work for other authorities such as NL (GAAP) as well.

### Interface

CLI (arelleCmdLine)

### Version

2.21.3

### Download

GitHub release (bundled Python)

### Operating System

Linux (Ubuntu 20.04)

**Comment by gmongelli** [comment] 2024-01-17 08:00
Thank you for reporting this issue.

Could you please give some references to the DK and NL specifications that explicitly allow this case.

In the ESEF plug-in there is a system that adapts the ESEF validations to the national authorities.

If this is confirmed by a lawful specification, we'll add an exception of the DK and NL authorities.

Best regards,

Greg

**Comment by IulianBogdan** [comment] 2024-01-17 14:48
In this section of the DK GAAP reporting manual: https://erhvervsstyrelsen.dk/sites/default/files/2022-03/Oversigt%20over%20tekniske%20regler%20ved%20indsendelse%20af%20digitale%20%C3%A5rsrapporter%202022_03_v2.0.pdf

It talks about _gsd:NameOfSubmittingEnterprise_ which is one of the facts in the error. Although it does not specifically state that it can be hidden, it's also not negating it, saying that the information must be reported, and it is not a visible part of the report.

**Comment by gmongelli** [comment] 2024-01-17 16:40
Hello,

The referenced specification says that the information must be reported, but I have not seen any statement saying that it is not a visible part of the report. Isn't there a specification where it appears more explicitly?

Having further analyzed the error message and the excerpt, I have seen that the inline XBRL instance refers to multiple XBRL taxonomies.

Do you confirm that there are multiple taxonomies referenced in DK filings?

In that case, we could refine our tests and for reports from Denmark only check if no elements from the ESEF extension or from the IFRS taxonomy are present in the `ix:hidden` part. This would fit your needs but still enforce the ESEF rules.

if we relied on the `TARGET="DKGAAP"` attribute as suggested by you, this could possibly let slip in IFRS or ESEF facts in `ix:hidden` sections simply because they have that attribute set.

Best regards,

Greg

**Comment by gmongelli** [comment] 2024-01-18 09:06
Hello,

The referenced specification says that the information must be reported, but I have not seen any statement saying that it is not a visible part of the report. Isn't there a specification where it appears more explicitly?

Having further analyzed the error message and the excerpt, I have seen that the inline XBRL instance refers to multiple XBRL taxonomies.

Do you confirm that there are multiple taxonomies referenced in DK filings?

In that case, we could refine our tests and for reports from Denmark only check if no elements from the ESEF extension or from the IFRS taxonomy are present in the `ix:hidden` part. This would fit your needs but still enforce the ESEF rules.

if we relied on the `TARGET="DKGAAP"` attribute as suggested by you, this could possibly let slip in IFRS or ESEF facts in `ix:hidden` sections simply because they have that attribute set.

Best regards,

Greg

**Comment by IulianBogdan** [comment] 2024-01-18 09:15
Hi Greg,

> The referenced specification says that the information must be reported, but I have not seen any statement saying that it is not a visible part of the report. Isn't there a specification where it appears more explicitly?

I'm afraid that's the best I could find, and I agree it's not clear enough, but the information is solid. We have a person in our team who worked as chief advisor for the authorities on DK GAAP. If this is the only obstacle, we can definitely set up a meeting for clarifications.

> Do you confirm that there are multiple taxonomies referenced in DK filings?

Correct, the use case I presented references both ESEF and DK GAAP.

> In that case, we could refine our tests and for reports from Denmark only check if no elements from the ESEF extension or from the IFRS taxonomy are present in the ix:hidden part. This would fit your needs but still enforce the ESEF rules.

Sounds good! We need this behavior for the DBA authority.

**Comment by fantastic-shaun** [comment] 2024-01-25 12:31
Hi

I believe that the UK's UKSEF regulations follow the same concepts as the DK authority.

It is multi-target XBRL. As per the DK instance, in the UKSEF there are mandatory tags required that if not present in the human-readable portion of the report must be added in a 'hidden' section.

The UK FRC taxonomies also require xbrli:segment elements which are not allowed in esef which uses xbrli:scenario elements.

So we are seeing package validation diverging from esef as well as xbrl instance validations.

I have used one of the simple 1 page UKSEF package documents supplied in the FRC draft conformance suite and it generates pages of validation errors.

[TC1_valid.zip](https://github.com/Arelle/Arelle/files/14051626/TC1_valid.zip)
[UKSEF - TC1-valid -- Arelle validation.txt](https://github.com/Arelle/Arelle/files/14051649/UKSEF.-.TC1-valid.--.Arelle.validation.txt)


Should we consider developing a separate validation suite for these types of packages?

I'd be happy to help where I can. No skills in XULE, and little experience in Python but can read code and know the iXBRL standards and EU regulations so can help testing.

Best wishes, Shaun

**Comment by austinmatherne-wk** [comment] 2024-01-26 02:13
The DK-GAAP validation errors that this issue was opened for appear to be resolved by specifically validating the ESEF (default) target instead of all targets.

```bash
python arelleCmdLine.py --package https://filings.xbrl.org/549300D2K6PKKKXVNN73/2023-09-30/ESEF/DK/0/APMM-2023-09-30-en.zip --parameters "authority=DBA" --plugins validate/ESEF --disclosureSystem esef-2023 --validate --file '[{"ixds": [{"file": "https://filings.xbrl.org/549300D2K6PKKKXVNN73/2023-09-30/ESEF/DK/0/APMM-2023-09-30-en.zip/APMM-2023-09-30-en/reports/APMM-2023-09-30-en.xhtml"}], "ixdsTarget": "(default)"}]'
```
vs. (same command except for the --file param)
```bash
python arelleCmdLine.py --package https://filings.xbrl.org/549300D2K6PKKKXVNN73/2023-09-30/ESEF/DK/0/APMM-2023-09-30-en.zip --parameters "authority=DBA" --plugins validate/ESEF --disclosureSystem esef-2023 --validate --file '[{"ixds": [{"file": "https://filings.xbrl.org/549300D2K6PKKKXVNN73/2023-09-30/ESEF/DK/0/APMM-2023-09-30-en.zip/APMM-2023-09-30-en/reports/APMM-2023-09-30-en.xhtml"}]}]'
```
or (same command except for the --file param)
```bash
python arelleCmdLine.py --package https://filings.xbrl.org/549300D2K6PKKKXVNN73/2023-09-30/ESEF/DK/0/APMM-2023-09-30-en.zip --parameters "authority=DBA" --plugins validate/ESEF --disclosureSystem esef-2023 --validate --file https://filings.xbrl.org/549300D2K6PKKKXVNN73/2023-09-30/ESEF/DK/0/APMM-2023-09-30-en.zip
```

For UKSEF I would expect a similar set of arguments (`authority=UKFRC`) to produce similar results; however, the UKFRC authority configuration hasn't been updated in some time, so it likely has issues ([target usage](https://github.com/Arelle/Arelle/blob/41f4fff8ed02eada71ace1379524740b810973f2/arelle/plugin/validate/ESEF/resources/authority-validations.json#L268) should be allowed now). On a related note, the HMRC validation plugin is actively being worked on after a hiatus and we have plans to create a DK-GAAP validation plugin later this year. Speculating, there's also the possibility that some of these reports could include a third ESG target in the future that requires its own plugin.

The command line syntax for handling multi-target documents or document sets in Arelle is awkward. We're planning to improve the situation, but it will take some time. Ultimately I want to be able to validate multi-target ESEF reports with something along the lines of the following:
```bash
python arelleCmdLine.py --file report.zip --plugins 'validate/ESEF | validate/DKGAAP' --disclosureSystems 'esef-2023 | dk-2023' --parameters "authority=DBA" --validate 
```
The key here is loading all targets, but each validation plugin would be smart enough to figure out the target it should run against and ignore the others (and throw an error if it fails to find any).

**Closed** 2024-02-13 09:06 UTC
Labels: bug
